import Answer from './Answer';
import Back from './Back';
import Clauses from './Clauses';
import Front from './Front';
import Greek from './Greek';
import HighlightParsing from './HighlightParsing';
import Parsing from './Parsing';
import PM from './PM';
import PrincipalParts from './PrincipalParts';
import Reference from './Reference';
import Translation from './Translation';
import Word from './Word';
import Test from './Test';
export * as Definition from './Definition';
export { Answer, Back, Clauses, Front, Greek, HighlightParsing, Parsing, PM, PrincipalParts, Reference, Translation, Word, Test };